### ISSUE TITLE
support on Mac

### ISSUE THREAD

**Issue by lytasky** [luser/dump_syms#13]
have you  compile the Breakpad Mac dump_syms tool?

**Comment by luser** [comment]
I'm not sure exactly what you're asking for here--this version of dump_syms is for dumping symbols from Windows PDB files, not Mac binaries.

**Comment by lytasky** [comment]
I need a version of dump_syms  that can run on Mac，but i don`t konw how to compile .   I just can compile the dump_syms that can run on Linux. Do you konw how to compile the   version of dump_syms  that can run on Mac. thanks

**Comment by luser** [comment]
The tool that's in the Breakpad repository has an xcode project:
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/tools/mac/dump_syms/
